import pandas as pd
import matplotlib.pyplot as plt
import os
os.makedirs("visualizations", exist_ok=True)
df = pd.read_excel("quotes_dataset.xlsx")
tags = df["tags"].str.split(", ").explode()
top_tags = tags.value_counts().head(5)
top_authors = df["author"].value_counts().head(5)
author_counts_sorted = df["author"].value_counts().sort_values(ascending=False)

# Chart 1: Top 5 Tags (Bar Chart)
plt.figure()
top_tags.plot(kind="bar")
plt.title("Top 5 Most Common Tags")
plt.xlabel("Tag")
plt.ylabel("Frequency")
plt.tight_layout()
plt.savefig("visualizations/top_tags_bar_chart.png")
plt.close()

# Chart 2: Author Quote Frequency (Line Plot)
plt.figure()
author_counts_sorted.plot(kind="line", marker="o")
plt.title("Quote Frequency by Author")
plt.xlabel("Author Index")
plt.ylabel("Number of Quotes")
plt.tight_layout()
plt.savefig("visualizations/author_quote_frequency_line.png")
plt.close()

# Chart 3: Top Authors (Horizontal Bar)
plt.figure()
top_authors.plot(kind="barh")
plt.title("Top 5 Authors by Quotes")
plt.xlabel("Number of Quotes")
plt.ylabel("Author")
plt.tight_layout()
plt.savefig("visualizations/top_authors_horizontal.png")
plt.close()

# Chart 4: Tag Distribution (Pie Chart)
plt.figure()
top_tags.plot(kind="pie", autopct="%1.1f%%")
plt.title("Top 5 Tags Distribution")
plt.ylabel("")
plt.tight_layout()
plt.savefig("visualizations/top_tags_pie.png")
plt.close()

print("✅ TASK 3 COMPLETED: All visualizations saved in the 'visualizations/' folder.")
